export const permissions = {
  usersManage: 'users.manage',
  organizationsRead: 'organizations.read',
  organizationsManage: 'organizations.manage',
  organizationsApprove: 'organizations.approve',
  catalogsRead: 'catalogs.read',
  catalogsManage: 'catalogs.manage',
  auctionsRead: 'auctions.read',
  auctionsCreate: 'auctions.create',
  auctionsUpdate: 'auctions.update',
  auctionsPublish: 'auctions.publish',
  reportsRead: 'reports.read',
  reportsExport: 'reports.export',
  analyticsRead: 'analytics.read',
  auditRead: 'audit.read',
} as const;
